"""Initial schema

Revision ID: fbfddde84811
Revises: 
Create Date: 2026-03-16 11:17:54.309520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbfddde84811'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('device_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('activity_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('app_name', sa.String(length=255), nullable=False),
    sa.Column('window_title', sa.String(length=500), nullable=True),
    sa.Column('process_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.Column('mouse_clicks', sa.BigInteger(), nullable=False),
    sa.Column('key_presses', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activity_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_sessions_app_name'), ['app_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_sessions_end_time'), ['end_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_sessions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_sessions_start_time'), ['start_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('screenshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('is_encrypted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['activity_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('screenshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_screenshots_captured_at'), ['captured_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_screenshots_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_screenshots_session_id'), ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('screenshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_screenshots_session_id'))
        batch_op.drop_index(batch_op.f('ix_screenshots_id'))
        batch_op.drop_index(batch_op.f('ix_screenshots_captured_at'))

    op.drop_table('screenshots')
    with op.batch_alter_table('activity_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_activity_sessions_start_time'))
        batch_op.drop_index(batch_op.f('ix_activity_sessions_id'))
        batch_op.drop_index(batch_op.f('ix_activity_sessions_end_time'))
        batch_op.drop_index(batch_op.f('ix_activity_sessions_app_name'))

    op.drop_table('activity_sessions')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_id'))

    op.drop_table('users')
    # ### end Alembic commands ###
